version: '3.8'

services:

  app:
    build:
      context: ./Server
      dockerfile: Dockerfile
    container_name: smartshift-api
    restart: always
    working_dir: /var/www
    volumes:
      - ./Server:/var/www
      - ./Server/.env:/var/www/.env
    networks:
      - smartshift-network

  webserver:
    image: nginx:stable-alpine
    container_name: smartshift-webserver
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./Server:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - smartshift-network
    depends_on:
      - app

networks:
  smartshift-network:
    driver: bridge