services:
  db:
    image: mysql:8.0
    container_name: smartshift-db
    restart: always
    environment:
      MYSQL_DATABASE: smartshift_db
      MYSQL_ROOT_PASSWORD: your_strong_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - smartshift-network

  app:
    image: ${DOCKERHUB_USERNAME:-mk67034}/smartshift-backend:${IMAGE_TAG:-latest}
    build:
      context: ./Server
      dockerfile: Dockerfile
      target: ${APP_BUILD_TARGET:-prod}
    container_name: smartshift-api
    restart: always
    working_dir: /var/www
    volumes:
      - ./Server/.env:/var/www/.env
      - ./Server/storage:/var/www/storage
    networks:
      - smartshift-network
    depends_on:
      - db

  edge:
    image: ${DOCKERHUB_USERNAME:-mk67034}/smartshift-edge:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: ./Edge/Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-/api/v1}
    container_name: smartshift-edge
    restart: always
    ports:
      - "80:80"
    networks:
      - smartshift-network
    depends_on:
      - app

networks:
  smartshift-network:
    driver: bridge

volumes:
  db_data: