services:
  db:
    image: mysql:8.0
    container_name: smartshift-db
    restart: always
    environment:
      MYSQL_DATABASE: smartshift_db
      MYSQL_ROOT_PASSWORD: your_strong_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - smartshift-network

  app:
    image: moustafak8/smartshift-backend:latest
    container_name: smartshift-api
    restart: always
    working_dir: /var/www
    volumes:
      - ./Server/.env:/var/www/.env
      - ./Server/storage:/var/www/storage
    networks:
      - smartshift-network
    depends_on:
      - db

  backend-web:
    image: nginx:stable-alpine
    container_name: smartshift-backend-web
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./Server/public:/var/www/public
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - smartshift-network
    depends_on:
      - app

  frontend:
    image: moustafak8/smartshift-frontend:latest
    container_name: smartshift-frontend
    restart: always
    ports:
      - "3000:80"
    networks:
      - smartshift-network

networks:
  smartshift-network:
    driver: bridge

volumes:
  db_data: