version: '3.8'

services:
  
  db:
    image: mysql:8.0
    container_name: smartshift-db
    restart: always
    environment:
      
      MYSQL_DATABASE: smartshift_db
      MYSQL_ROOT_PASSWORD: your_strong_password
    volumes:
      
      - db_data:/var/lib/mysql
    networks:
      - smartshift-network


  app:
    build:
      context: ./Server
      dockerfile: Dockerfile
    container_name: smartshift-api
    restart: always
    working_dir: /var/www
    volumes:
      - ./Server/.env:/var/www/.env
     
      - ./Server/storage:/var/www/storage
    networks:
      - smartshift-network
    depends_on:
      - db

  
  webserver:
    image: nginx:stable-alpine
    container_name: smartshift-webserver
    restart: always
    ports:
      - "80:80"
    volumes:
      
      - ./Server/public:/var/www/public
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - smartshift-network
    depends_on:
      - app

networks:
  smartshift-network:
    driver: bridge

volumes:
  db_data: 